# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from liteagent.network.protos import coordinator_pb2 as liteagent_dot_network_dot_protos_dot_coordinator__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in liteagent/network/protos/coordinator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkstationCoordinatorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/liteagent.WorkstationCoordinator/Ping',
                request_serializer=liteagent_dot_network_dot_protos_dot_coordinator__pb2.PingRequest.SerializeToString,
                response_deserializer=liteagent_dot_network_dot_protos_dot_coordinator__pb2.PingResponse.FromString,
                _registered_method=True)
        self.DispatchTask = channel.unary_unary(
                '/liteagent.WorkstationCoordinator/DispatchTask',
                request_serializer=liteagent_dot_network_dot_protos_dot_coordinator__pb2.TaskRequest.SerializeToString,
                response_deserializer=liteagent_dot_network_dot_protos_dot_coordinator__pb2.TaskResponse.FromString,
                _registered_method=True)


class WorkstationCoordinatorServicer:
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Verifies connection and checks version compatibility
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DispatchTask(self, request, context):
        """Dispatches a high-complexity sub-task from Edge to Workstation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkstationCoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=liteagent_dot_network_dot_protos_dot_coordinator__pb2.PingRequest.FromString,
                    response_serializer=liteagent_dot_network_dot_protos_dot_coordinator__pb2.PingResponse.SerializeToString,
            ),
            'DispatchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DispatchTask,
                    request_deserializer=liteagent_dot_network_dot_protos_dot_coordinator__pb2.TaskRequest.FromString,
                    response_serializer=liteagent_dot_network_dot_protos_dot_coordinator__pb2.TaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'liteagent.WorkstationCoordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('liteagent.WorkstationCoordinator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkstationCoordinator:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liteagent.WorkstationCoordinator/Ping',
            liteagent_dot_network_dot_protos_dot_coordinator__pb2.PingRequest.SerializeToString,
            liteagent_dot_network_dot_protos_dot_coordinator__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DispatchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/liteagent.WorkstationCoordinator/DispatchTask',
            liteagent_dot_network_dot_protos_dot_coordinator__pb2.TaskRequest.SerializeToString,
            liteagent_dot_network_dot_protos_dot_coordinator__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
